### ISSUE TITLE
Modify features for H1

### ISSUE THREAD

**Issue by DanielWestgaard** [DanielWestgaard/ml-pred#28]
Modify (and potentially add) features for Hypothesis 1, to make sure a model has better opportunities for successfully detecting patterns for it.

- [ ] Add these specific features (meaning new functions to calculate them in FG, and update h1/config.yml):
    ```yml
    - spread_analysis (bid-ask spreads vary significantly by session)
    - liquidity_proxies (volume relative to typical session volume)
    - session_transition_flags (15-30 minutes around major opens/closes)
    - economic_news_proximity (within 30 minutes of scheduled releases)
    - price_clustering (tends to cluster at round numbers)
    - time_since_last_significant_move
    - intrabar_volatility (high-low range relative to typical)
    ```
- [x] More granular feature selection, both in config.yml, but also for the needed features in H1:
    ```yml
    hypothesis:
      name: session_based_tod_anomalies
      
    required_features:
      moving_averages: [5, 20, 50]  # Only these periods
      time_features: ['hour_sin', 'hour_cos', 'session']
      volatility_features: ['atr', 'volatility_regime']
      custom_features: ['spread_proxy', 'session_volume_ratio']
    ```
    - Added more granular feature selection by implementing a check_feature_specification(), in data_utils, that checks and finds out what do potentially "do" with the hypothesis configuration.
- [ ] Add Session-specific normalization. I'm not sure how or the benefit, but this is part of the task. 
    ```
    def session_aware_normalization(self):
        """Normalize features within each trading session separately"""
        for session in ['asian', 'london', 'ny']:
            session_mask = self.df['session'] == session
            # Apply your existing normalization methods per session
    ```
- [x] Enhance volume profile for Forex:
    ```
    # In your volume_profile method, consider:
    # FX doesn't have traditional volume, so you might use tick volume or spread-based proxies
    def fx_activity_profile(self, lookback=20):
        """Create activity profile using price movement and spread changes"""
        # Use high-low range as activity proxy
        self.df['activity'] = (self.df['high'] - self.df['low']) / self.df['close']
    ```
