### ISSUE TITLE
Configure hypothesis with data path and model

### ISSUE THREAD

**Issue by DanielWestgaard** [DanielWestgaard/ml-pred#44]
Currently, we have to both use --data-engineer and then the --hypothesis flags. Like this:
```python
python main.py --engineer-data 'storage/data/capital_com/raw/raw_GBPUSD_m_20250101_20250523.csv' --hypothesis "hypothesis/1_session_based_tod_anomalies/config.yml"
```
and having this logic:
```python
if args.engineer_data:  # with path to raw dataset
        save_cleaned_data = True
        if args.hypothesis:  # with path to hypothesis config
           # etc...
```
and then another flag for training a model on processed/engineered data.

**However**, I think it would be much better to only need the --hypothesis flag with config specifying raw or processed data (based on use).
Perhaps calling it like this:
```python
python main.py --hypothesis "hypothesis/1_session_based_tod_anomalies/config.yml"
```
and then the config.yml contains something like this:
```yml
name: <name-of-the-hypothesis>

required_features:
  feature_name_1: [5, 20, 50]                                # Only these periods of that feature
  feature_name_2: []                                         # All "features" from this feature method
  feature_name_3: ['feature_value_1', 'feature_value_2']     # Only these features from the feature method

# TODO:
data_path:
  - raw: "<local-path-do-raw-data>"  # This means we need want to use the full data pipeline
  - processed: "<local-path-do-processed-data>"  # This means we need want to train a ml model
  # Having both (raw file path and processed but empty) means we want to run Data Pipeline and use processed data later - eg. for training a model

# TODO:
model_name: <name-of-ml-model>
  parameters:                                                # Empty means using 'default' hyperparameter values
    - n_estimators: 100
    - max_depth: 12
```
